namespace ThousandAcreWoods.UI.Components.AnimatedFonts.Kalam;

public static class KalamFontFamily
{

    public static Func<char, AnimatedLetter?> FontFamily => ch => ch switch
    {
        'A' => new _A(),
        'B' => new _B(),
        'C' => new _C(),
        'D' => new _D(),
        'E' => new _E(),
        'F' => new _F(),
        'G' => new _G(),
        'H' => new _H(),
        'I' => new _I(),
        'J' => new _J(),
        'K' => new _K(),
        'L' => new _L(),
        'M' => new _M(),
        'N' => new _N(),
        'O' => new _O(),
        'P' => new _P(),
        'Q' => new _Q(),
        'R' => new _R(),
        'S' => new _S(),
        'T' => new _T(),
        'U' => new _U(),
        'V' => new _V(),
        'W' => new _W(),
        'X' => new _X(),
        'Y' => new _Y(),
        'Z' => new _Z(),
        'Æ' => new _Æ(),
        'Ø' => new _Ø(),
        'Å' => new _Å(),

        'a' => new a(),
        'b' => new b(),
        'c' => new c(),
        'd' => new d(),
        'e' => new e(),
        'f' => new f(),
        'g' => new g(),
        'h' => new h(),
        'i' => new i(),
        'j' => new j(),
        'k' => new k(),
        'l' => new l(),
        'm' => new m(),
        'n' => new n(),
        'o' => new o(),
        'p' => new p(),
        'q' => new q(),
        'r' => new r(),
        's' => new s(),
        't' => new t(),
        'u' => new u(),
        'v' => new v(),
        'w' => new w(),
        'x' => new x(),
        'y' => new y(),
        'z' => new z(),
        'æ' => new æ(),
        'ø' => new ø(),
        'å' => new å(),

        '!' => new EXCLAMATIONMARK(),
        '"' => new CITATIONMARK(),
        '#' => new HASHTAG(),
        '%' => new PERCENTAGE(),
        '&' => new AMPERSAND(),
        '/' => new SLASH(),
        '(' => new PARENTHESISSTART(),
        ')' => new PARENTHESISEND(),
        '[' => new BRACKETSTART(),
        ']' => new BRACKETEND(),
        '{' => new CURLYBRACKETSTART(),
        '}' => new CURLYBRACKETEND(),

        '=' => new EQUALS(),
        '?' => new QUESTIONMARK(),
        '\\' => new BACKSLASH(),
        '|' => new BAR(),
        '@' => new AT(),
        '$' => new DOLLARSIGN(),

        '*' => new STAR(),
        '<' => new LT(),
        '>' => new GT(),
        '-' => new MINUS(),
        '+' => new PLUS(),

        '.' => new DOT(),
        ',' => new COMMA(),
        ';' => new SEMICOLON(),
        ':' => new COLON(),
        '¿' => new ESP_QUESTIONMARK(),
        '¡' => new ESP_EXCLAMATIONMARK(),

        ' ' => new SPACE(),
        _ => null
    };


}
